name: portfolio_2024
description: "Toby Prosser's Portfolio"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  firebase_core: ^2.24.2
  flutter_widget_from_html_core: any
  firebase_storage: ^11.6.0
  cached_network_image: ^3.4.1

  flutter:
    sdk: flutter

  provider: ^6.1.1
  rive: ^0.12.3
  video_player: ^2.8.2
  google_fonts: ^6.1.0
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.6
  youtube_player_iframe: ^4.0.4
  fwfh_webview: ^0.14.8
  just_audio: ^0.9.36
  url_launcher: ^6.3.0
  image_network: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/portfoliocontrol.riv
